config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :blog_pests

 #get "blog_pests/new", to: "blog_pests#new", as: :new_blog_pest
 #get "/blog_pests/:id/edit", to: "blog_pests#edit", as: :edit_blog_pest
 #patch "/blog_pests/:id", to: "blog_pests#update"
 #delete "/blog_pests/:id", to: "blog_pests#destroy"
 #get "/blog_pests/:id", to: "blog_pests#show", as: :blog_pest
 #post "/blog_pests", to: "blog_pests#create", as: :blog_pests
 
  # Defines the root path route ("/")
 root "blog_pests#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_pest.rb
class BlogPest < ApplicationRecord
    # adds rich text to the application
    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, -> { order(Arel.sql("published_at DESC NULLS LAST")).order(updated_at: :desc) }
    scope :draft, -> { where(published_at: nil) }
    scope :published, -> { where("published_at <= ?", Time.current) }
    scope :scheduled, -> { where("published_at > ?", Time.current) }

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at && published_at > Time.current
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_pests_controller.rb
class BlogPestsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_pest, except: [:index, :new, :create]

    def index
        @blog_pests = user_signed_in? ? BlogPest.all.sorted : BlogPest.published.sorted
    end

    def show
    end

    def new
        @blog_pest = BlogPest.new
    end

    def create
        @blog_pest = BlogPest.new(blog_pest_params)
        if @blog_pest.save
            redirect_to @blog_pest
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @blog_pest.update(blog_pest_params)
            redirect_to @blog_pest
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @blog_pest.destroy
        redirect_to root_path
    end

    private
        def blog_pest_params
            params.require(:blog_pest).permit(:title, :content, :published_at)
        end

        def set_blog_pest
            @blog_pest = user_signed_in? ? BlogPest.find(params[:id]) : BlogPest.published.find(params[:id])
            rescue ActiveRecord::RecordNotFound
            redirect_to root_path
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_pests/_form.html.erb
<%= form_with model: blog_pest do |form|%>
    <% if form.object.errors.any? %>
        <div>
            <% form.object.errors.full_messages.each do |message| %>
            <div><%= message%></div>
            <% end %>
        </div>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :content%>
        <%= form.rich_text_area :content%>
    </div>
    <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
    </div>
    <%= form.button%>
    
<% end %>

app/views/blog_pests/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: {blog_pest: @blog_pest}%>
<%= button_to "Delete", @blog_pest, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_pests/index.html.erb
<h1>My Blog</h1>

<%= link_to "Create", new_blog_pest_path(@blog_pest) if user_signed_in?%>

<% @blog_pests.each do |blog_pest| %>
   
   <div>

        <% if blog_pest.draft? %>
            <div class = "p-2 rounded bg-gray-100 text-gray-900"><h2><%= link_to blog_pest.title, blog_pest%></h2>Draft</div>
        <% elsif blog_pest.scheduled?%>
            <div class = "p-2 rounded bg-blue-100 text-blue-900"><h2><%= link_to blog_pest.title, blog_pest%></h2>Scheduled</div>
            <h2><%= link_to blog_pest.title, blog_pest%></h2>
        <% else %>
            <h2><%= link_to blog_pest.title, blog_pest%></h2>
        <% end %>

        <%= blog_pest.content%>

    </div>

<% end %>

app/views/blog_pests/new.html.erb
<h1>New Blog Pest</h1>

<%= link_to "Index", root_path %>

<%= render partial: "form", locals: {blog_pest: @blog_pest}%>

app/views/blog_pests/show.html.erb
<h1><%= @blog_pest.title%></h1>
<h2><%= @blog_pest.content%></h2>
<%= link_to "Index", root_path%>
<%= link_to "Edit", edit_blog_pest_path(@blog_pest) if user_signed_in?%>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "prose mx-auto">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>

    <%= yield %>
    
  </body>
</html>